---
- hosts: backend
  become: true
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone backend repository
      git:
        repo: "https://github.com/kholodihor/mindlab-platform-backend"
        dest: /var/www/backend
        version: main

    - name: Install Node.js dependencies
      command: npm install
      args:
        chdir: /var/www/backend

    - name: Start backend service with PM2
      command: pm2 start app.js
      args:
        chdir: /var/www/backend

- hosts: frontend
  become: true
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone frontend repository
      git:
        repo: "https://github.com/kholodihor/mindlab-platform"
        dest: /var/www/frontend
        version: main

    - name: Install Node.js dependencies for frontend
      command: npm install
      args:
        chdir: /var/www/frontend

    - name: Build frontend
      command: npm run build
      args:
        chdir: /var/www/frontend

    - name: Copy build files to web server
      copy:
        src: /var/www/frontend/build/
        dest: /var/www/frontend/public/
